package mathInterface;

public enum GenePosition {
	
	USER_SCORE,
	FEEDBACK_DELAY,
	TEXT_COLOR_R,
	TEXT_COLOR_G,
	TEXT_COLOR_B, 
	VERIFICATION_MODALITY,
	VERIFICATION_TYPE, 
	P_ELABORATE, 
	DELAY_UNTIL_ELABORATE, 
	P_ATTRIBUTE_ISOLATION, 
	ATTRIBUTE_ISOLATION_DURATION, 
	P_DIRECTIVE, 
	DIRECTIVE_DELAY, 
	P_CORRECT_RESPONSE, 
	CORRECT_RESPONSE_DELAY, 
	P_ERROR_FLAG, 
	ERROR_FLAG_DELAY, 
	P_ALLOW_RESUBMIT;
	

}
